// Generated by gencpp from file brx_ik_solver/IkControlInput.msg
// DO NOT EDIT!


#ifndef BRX_IK_SOLVER_MESSAGE_IKCONTROLINPUT_H
#define BRX_IK_SOLVER_MESSAGE_IKCONTROLINPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace brx_ik_solver
{
template <class ContainerAllocator>
struct IkControlInput_
{
  typedef IkControlInput_<ContainerAllocator> Type;

  IkControlInput_()
    : header()
    , pose()
    , solve_type()
    , lock_joint()
    , lock_values()  {
    }
  IkControlInput_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , solve_type(_alloc)
    , lock_joint(_alloc)
    , lock_values(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _solve_type_type;
  _solve_type_type solve_type;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _lock_joint_type;
  _lock_joint_type lock_joint;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _lock_values_type;
  _lock_values_type lock_values;





  typedef boost::shared_ptr< ::brx_ik_solver::IkControlInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brx_ik_solver::IkControlInput_<ContainerAllocator> const> ConstPtr;

}; // struct IkControlInput_

typedef ::brx_ik_solver::IkControlInput_<std::allocator<void> > IkControlInput;

typedef boost::shared_ptr< ::brx_ik_solver::IkControlInput > IkControlInputPtr;
typedef boost::shared_ptr< ::brx_ik_solver::IkControlInput const> IkControlInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brx_ik_solver::IkControlInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brx_ik_solver::IkControlInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::brx_ik_solver::IkControlInput_<ContainerAllocator1> & lhs, const ::brx_ik_solver::IkControlInput_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.solve_type == rhs.solve_type &&
    lhs.lock_joint == rhs.lock_joint &&
    lhs.lock_values == rhs.lock_values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::brx_ik_solver::IkControlInput_<ContainerAllocator1> & lhs, const ::brx_ik_solver::IkControlInput_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace brx_ik_solver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::brx_ik_solver::IkControlInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brx_ik_solver::IkControlInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brx_ik_solver::IkControlInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brx_ik_solver::IkControlInput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brx_ik_solver::IkControlInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brx_ik_solver::IkControlInput_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brx_ik_solver::IkControlInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "535926b983805427fbc7baab7e4cdf0a";
  }

  static const char* value(const ::brx_ik_solver::IkControlInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x535926b983805427ULL;
  static const uint64_t static_value2 = 0xfbc7baab7e4cdf0aULL;
};

template<class ContainerAllocator>
struct DataType< ::brx_ik_solver::IkControlInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brx_ik_solver/IkControlInput";
  }

  static const char* value(const ::brx_ik_solver::IkControlInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brx_ik_solver::IkControlInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Pose pose\n"
"string solve_type\n"
"bool[] lock_joint\n"
"float64[] lock_values\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::brx_ik_solver::IkControlInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brx_ik_solver::IkControlInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.solve_type);
      stream.next(m.lock_joint);
      stream.next(m.lock_values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IkControlInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brx_ik_solver::IkControlInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brx_ik_solver::IkControlInput_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "solve_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.solve_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lock_joint: ";
    if (v.lock_joint.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lock_joint.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.lock_joint[i]);
    }
    if (v.lock_joint.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lock_values: ";
    if (v.lock_values.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lock_values.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.lock_values[i]);
    }
    if (v.lock_values.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRX_IK_SOLVER_MESSAGE_IKCONTROLINPUT_H
